"""Created user and Table relationship

Revision ID: 27c99c7e5814
Revises: 890b9fd76024
Create Date: 2023-10-08 18:14:55.075772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27c99c7e5814'
down_revision = '890b9fd76024'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
