"""updated users table

Revision ID: 621ff569a884
Revises: 280dad96d07e
Create Date: 2023-10-06 11:18:57.179616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '621ff569a884'
down_revision = '280dad96d07e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone_number', sa.Integer(), nullable=True))
    op.drop_column('user', 'role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sa.VARCHAR(length=20), nullable=False))
    op.drop_column('user', 'phone_number')
    # ### end Alembic commands ###
